#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : traceroute
Version  : 2.1.0
Release  : 15
URL      : https://sourceforge.net/projects/traceroute/files/traceroute/traceroute-2.1.0/traceroute-2.1.0.tar.gz
Source0  : https://sourceforge.net/projects/traceroute/files/traceroute/traceroute-2.1.0/traceroute-2.1.0.tar.gz
Summary  : Traces the route taken by packets over an IPv4/IPv6 network
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: traceroute-bin = %{version}-%{release}
Requires: traceroute-license = %{version}-%{release}
Requires: traceroute-man = %{version}-%{release}
Patch1: 0000-fix-prefix.patch

%description
The traceroute utility displays the route used by IP packets on their
way to a specified network (or Internet) host.  Traceroute displays
the IP number and host name (if possible) of the machines along the
route taken by the packets.  Traceroute is used as a network debugging
tool.  If you're having network connectivity problems, traceroute will
show you where the trouble is coming from along the route.

Install traceroute if you need a tool for diagnosing network connectivity
problems.

%package bin
Summary: bin components for the traceroute package.
Group: Binaries
Requires: traceroute-license = %{version}-%{release}

%description bin
bin components for the traceroute package.


%package license
Summary: license components for the traceroute package.
Group: Default

%description license
license components for the traceroute package.


%package man
Summary: man components for the traceroute package.
Group: Default

%description man
man components for the traceroute package.


%prep
%setup -q -n traceroute-2.1.0
cd %{_builddir}/traceroute-2.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589409803
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1589409803
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/traceroute
cp %{_builddir}/traceroute-2.1.0/COPYING %{buildroot}/usr/share/package-licenses/traceroute/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/traceroute-2.1.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/traceroute/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/traceroute

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/traceroute/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/traceroute/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/traceroute.8
